spring:
    jpa:
        database: MYSQL
        database-platform:
        show-sql: true 
        hibernate:
            ddl-auto: none 
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost/products?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password:
    main:
        banner-mode: off

logging:
  level:
    '[org.springframework.web]':
        servlet:
            mvc:
                '[method.annotation]': TRACE 